// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsntbmnfWuYjduM0lKkja1Mpd7xRLd9BM',
    appId: '1:194891274006:web:80d2c6d302681609556237',
    messagingSenderId: '194891274006',
    projectId: 'idea-concept',
    authDomain: 'idea-concept.firebaseapp.com',
    storageBucket: 'idea-concept.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHOPXQC2APFLokhRjeSc4UffBfU1KKCU0',
    appId: '1:194891274006:android:3de3ec29c82414a7556237',
    messagingSenderId: '194891274006',
    projectId: 'idea-concept',
    storageBucket: 'idea-concept.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj8EgcTzL2qr01k3_3Y0vqeb70YY29xbk',
    appId: '1:194891274006:ios:1ff59395c5bcd1f8556237',
    messagingSenderId: '194891274006',
    projectId: 'idea-concept',
    storageBucket: 'idea-concept.firebasestorage.app',
    iosBundleId: 'com.example.flutterTaskIdea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj8EgcTzL2qr01k3_3Y0vqeb70YY29xbk',
    appId: '1:194891274006:ios:1ff59395c5bcd1f8556237',
    messagingSenderId: '194891274006',
    projectId: 'idea-concept',
    storageBucket: 'idea-concept.firebasestorage.app',
    iosBundleId: 'com.example.flutterTaskIdea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsntbmnfWuYjduM0lKkja1Mpd7xRLd9BM',
    appId: '1:194891274006:web:c16295e08dd9b82d556237',
    messagingSenderId: '194891274006',
    projectId: 'idea-concept',
    authDomain: 'idea-concept.firebaseapp.com',
    storageBucket: 'idea-concept.firebasestorage.app',
  );
}
